language: python

python:
  - 3.8

services:
  postgresql
addons:
  postgresql: '9.5'

install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - cp contrib/env-sample .env

befor_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8
  - pipenv run pytest --cov=rango
after_sucess:
  - pipenv run codecov