# Generated by Django 3.0.8 on 2020-07-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangomain', '0002_auto_20200720_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
