# Generated by Django 3.0.8 on 2020-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangomain', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
