# Generated by Django 3.0.8 on 2020-07-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangomain', '0004_auto_20200720_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
